### ISSUE TITLE
 Graphic of mobiles remains on screen, when in fact they are not there.

### ISSUE THREAD

**Issue by daedel** [Pack4Duck/ClassicUO#1451]
When using ClassicUO on the POL emulator (www.polserver.com) I get a strange error with graphics staying on the screen. For example, there is a situation where I am chasing another player. And I see a graphic of a player standing on the screen, and thinking it's a player I attack it. However, it turns out that this player is not on the screen here. Only his graphic remains and in reality the player has escaped far away.

So it looks like there is a bug where the player's graphics are left on the screen. I wonder if this bug only happens when playing on Ultima servers that use POL eumulator.

Perhaps someone knows if this problem is widespread?

**Comment by lvcmenezes** [comment]
The problem is that POL only handles packages in a 18x18 window and ClassicUO expects it to be 24x24. When something happens in this margin, POL does not send the packages anymore and ClassicUO will not acknowledge the change - leaving you in an old state.

I fixed this once by sending the package at Login time informing that ClassicUO should handle a window of 18x18 and no longer 24x24, as in its default configurations. This fixed the problem, although it reduces the distance you see in the client. I will look up what package it is (I don't have the code anymore) and let you know if I find it.

**Comment by daedel** [comment]
@lvcmenezes  I would appreciate it!

**Comment by lvcmenezes** [comment]
Here is the documentation:
http://docs.polserver.com/packets/index.php?Packet=0xC8

I really don't have the code anymore. Hope it helps! ;)

**Comment by daedel** [comment]
@lvcmenezes  So if I set in calssicuo UpdateRange to 18? It's should works?

**Comment by lvcmenezes** [comment]
Yep you could alternatively also hardcode that on your ClassicUO UpdateRange. :D

**Comment by andreakarasho** [comment]
ClassicUO update the viewrange based on server response:
https://github.com/ClassicUO/ClassicUO/blob/dev/src/Network/PacketHandlers.cs#L2329
