### ISSUE TITLE
ClassicUO launcher cannot be opened on a Mac M1

### ISSUE THREAD

**Issue by canterberry** [Pack4Duck/ClassicUO#1558]
According to https://github.com/ClassicUO/ClassicUO/issues/1501, this is by design. However, since M1 has been the dominant architecture on Mac since 2020 (2+ years), I propose that it's long overdue to begin supporting M1 Macs.

# Steps to Reproduce

 1. Visit https://www.classicuo.eu.
 2. Click the **macOS** button to download the macOS version of ClassicUO.
 3. Navigate to the Downloads folder via Finder and attempt to open **ClassicUOLauncher.app**.

## Actual Result

<img width="261" alt="Screen Shot 2022-09-07 at 12 19 30" src="https://user-images.githubusercontent.com/4053794/188959921-90e425ea-a488-439b-bdfb-265995872c69.png">

## Expected Result

ClassicUO launcher opens successfully.

**Comment by enribortoletto** [comment]
It's a pity! I hope it will be fixed :/

**Comment by bum404** [comment]
When?

**Comment by albertoacj** [comment]
x86 mac have the same issue

**Comment by ray77** [comment]
It runs fine, but Rosetta Emulation is needed. Almost all modern Macs are ARM-based, so it makes sense to support M1 CPU.

**Comment by bum404** [comment]
Did you try Mobile UO?

Ray ***@***.***>, 18 Ara 2022 Paz, 11:43 tarihinde şunu yazdı:

**Comment by thurisaz-org** [comment]
This problem is probably not fixable. Many .net apps rely on DLLs compiled for x86 or x64 arch. Even though a pure .net might work, if you touch a library that uses native code, and there is a lot, it won't work. The only "fix" is for MS to go and create an M1 version of .net or mono with all the native dll's compiled for M1, which isn't just a flip-the-flag fix.

https://learn.microsoft.com/en-us/visualstudio/mac/uninstall-net-2019?view=vsmac-2022
On Apple Silicon machines (also known as M1, M2, or ARM), Visual Studio for Mac 8.10 does not support the .NET 6 Arm64 SDK. .NET 5 and .NET Core 3.1 x64 SDKs are supported.

**Comment by SaschaKP** [comment]
I've compiled a cuo for Raspberry PI4, that uses ARM in a RISC environment, so very little difference from M1 from the point of view of useability/architecture.

You'll have to compile it for the proper environment yourself I suppose. (and use mono instead of VS .net)

**Comment by andreakarasho** [comment]
I'm aware that ClassicUOLauncher runs on x64 CPU only. A new CPU arch was not expected at the time.
There are no plans to support this platform at the moment for various reasons:
- I don't own a physic mac with m1 mounted
- time

**Comment by punteroanull** [comment]
> I've compiled a cuo for Raspberry PI4, that uses ARM in a RISC environment, so very little difference from M1 from the point of view of useability/architecture.
> 
> You'll have to compile it for the proper environment yourself I suppose. (and use mono instead of VS .net)

I'm trying to compile for ARM64 (for Windows on ARM) but it gaves me some errors, did you compile external libraries in ARM too?
