### ISSUE TITLE
Failure to clone ClassicUO repository - (lib/FAudio).

### ISSUE THREAD

**Issue by p145085** [Pack4Duck/ClassicUO#1564]
**Describe the bug**
When attempting to clone a forked repository of ClassicUO into Visual Studio 2022 it takes a long time to 'resolve deltas' and eventually displays the error shown below 'Screenshots'.

**To Reproduce**
Copy the URL for 'ClassicUO' repository, start Visual Studio 2022 and choose 'Clone a repository', enter the details and start the clone.

**Expected behavior**
I expected it to clone the repository no problem.

**Screenshots**
https://imgur.com/a/Csh01HX

**Information (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19044.2006]
 - ClassicUO Version: N/A.

**Comment by gaechti** [comment]
not a bug. cuo uses an older fna version because metal? support is removed in newer ones. and fna submodule has git:// instead of https://, but github removed git:// support

easyest fix, is this git bash command

git config --global url."https://".insteadOf git://
git clone --recursive -b dev https://github.com/ClassicUO/ClassicUO.git

**Comment by p145085** [comment]
> not a bug. cuo uses an older fna version because metal? support is removed in newer ones. and fna submodule has git:// instead of https://, but github removed git:// support
> 
> easyest fix, is this git bash command
> 
> git config --global url."https://".insteadOf git:// git clone --recursive -b dev https://github.com/ClassicUO/ClassicUO.git

Thanks, that solved it. Closing.
